# Generated by Django 2.2.4 on 2019-08-15 20:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
